### PR TITLE
fix #653 Skip elements that does not have `.offsetParent` correctly

### LINKED ISSUE #653: Position breaks when the reference has an SVG element directly inside
### CodePen demo

https://codepen.io/anon/pen/djNawe

(remove the SVG element to see the difference)
(if you wrap the SVG in a `div`, it also works)

### Steps to reproduce the problem

1.  Put the popover inside its reference;
2.  Make the reference absolutely positioned and give it some `top` and `left` values;
3.  Put an SVG element inside the reference.

### What is the expected behavior?

Removing the SVG element makes it work as expected:
image

### What went wrong?

When it has an SVG element, it breaks:

screen shot 2018-07-21 at 21 07 14

### Any other comments?

I'm trying to integrate Popper.js on my component library (https://reakit.io).

### PR DESCRIPTION
**Pull request by piglovesyou**
Some element (eg. svg) does not have `.offsetParent` so we can try the
nextElementSibling of it

Closes #653

### CODE REVIEW

**Comment by piglovesyou** [comment]
Boof

**Comment by piglovesyou** [comment]
Ready to be reviewed.

File: packages/popper/src/utils/getOffsetParent.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default function getOffsetParent(element) {
   const noOffsetParent = isIE(10) ? document.body : null;
 
   // NOTE: 1 DOM access here
-  let offsetParent = element.offsetParent;
+  let offsetParent = element.offsetParent || null;
```
Comment (glebm) [inline packages/popper/src/utils/getOffsetParent.js]: If `element.offsetParent` is 0, the `offsetParent` variable will be `null`. Is this the intent?

Comment (FezVrasta) [reply packages/popper/src/utils/getOffsetParent.js]: offsetParent is not a number, is an Element

Comment (glebm) [reply packages/popper/src/utils/getOffsetParent.js]: Ah, thanks
