### PR TITLE
Fix offset parent calculation for hidden elements

### LINKED ISSUE #537: Incorrect offset container used when first child of common parent is a hidden input
### CodePen demo

https://codepen.io/anon/pen/BYyjNM

### Steps to reproduce the problem

1.  Include a hidden input as the first child of the offset container of the elements.

### What is the expected behavior?

The "reference" and "popper" elements are aligned.

### What went wrong?

A hidden input's `offsetParent` is null, causing incorrect offset container to be chosen for the offsets calculations.

### Any other comments?

[This is the place](https://github.com/FezVrasta/popper.js/blob/150ef056629b171b96e5f2bcf6316d25ff0a146f/packages/popper/src/utils/isOffsetContainer.js#L9) where element's first child is arbitrarily chosen for a test if the element is an offset container. I think, it needs to use a child which is actually rendered.

### PR DESCRIPTION
**Pull request by RKushnir**
Fixes #537

### CODE REVIEW

File: packages/popper/src/utils/getOffsetParent.js [hunk 1]
```diff
@@ -8,7 +8,10 @@ import getStyleComputedProperty from './getStyleComputedProperty';
  */
 export default function getOffsetParent(element) {
   // NOTE: 1 DOM access here
-  const offsetParent = element && element.offsetParent;
+  let offsetParent = element && element.offsetParent;
+  while (offsetParent === null && element.nextElementSibling) {
```
Comment (FezVrasta) [inline packages/popper/src/utils/getOffsetParent.js]: Great! May you just add a small comment to explain why this is needed, for future reference?

File: packages/popper/tests/unit/getOffsetParent.js [hunk 2]
```diff
@@ -24,4 +24,23 @@ describe('utils/getOffsetParent', () => {
...
+
+  it('first child element is hidden', () => {
+    const innerNode = document.createElement('div');
+    innerNode.style.display = 'none';
+    const nextSibling = document.createElement('div');
+    node.style.position = 'absolute';
+    node.appendChild(innerNode);
+    node.appendChild(nextSibling);
+
+    expect(getOffsetParent(innerNode)).to.equal(node);
```
Comment (FezVrasta) [inline packages/popper/tests/unit/getOffsetParent.js]: I see IE10 is failing here, I wonder if it just defines `offsetParent` even to hidden elements.... In that case I think the assertion should check to make sure the returned node is the first with a `offsetParent` property set.

Comment (RKushnir) [reply packages/popper/tests/unit/getOffsetParent.js]: If it defined `offsetParent`, wouldn't the assertion still be correct? It seems to me, that would just behave like the previous test case('element is inside positioned element').

Comment (RKushnir) [reply packages/popper/tests/unit/getOffsetParent.js]: So I figured the `offsetParent` for hidden elements in IE10 is `body`.

Comment (FezVrasta) [reply packages/popper/tests/unit/getOffsetParent.js]: So for IE10 we should have something like:

Comment (RKushnir) [reply packages/popper/tests/unit/getOffsetParent.js]: @FezVrasta A kindly reminder in case you forgot 🙂 I'd like to finish this while it's still fresh.

File: packages/popper/src/utils/getOffsetParent.js [hunk 3]
```diff
@@ -7,8 +8,19 @@ import getStyleComputedProperty from './getStyleComputedProperty';
...
-  const offsetParent = element && element.offsetParent;
+  let offsetParent = element.offsetParent;
+  // Skip hidden elements which don't have an offsetParent
+  while (offsetParent === noOffsetParent && element.nextElementSibling) {
+    offsetParent = (element = element.nextElementSibling).offsetParent;
+  }
+
   const nodeName = offsetParent && offsetParent.nodeName;
 
   if (!nodeName || nodeName === 'BODY' || nodeName === 'HTML') {
```
Comment (FezVrasta) [inline packages/popper/src/utils/getOffsetParent.js]: Just to make CodeClimate happy, may you refactor the branch below to be:

Comment (RKushnir) [reply packages/popper/src/utils/getOffsetParent.js]: CodeClimate is green and delighted now.
